# SMTP credentials
smtp:
  from:       alerts@mltool.com
  to:         ["alice@example.com"]
  host:       smtp.gmail.com
  port:       587
  user:       alerts@mltool.com
  password:   "YOUR_APP_PASSWORD"

# Scraper + matcher
scraper:
  base_url:   "https://autobid.de/en/search-results?e367=1&sortingType=auctionStartDate-ASCENDING"
  max_pages:  130
  headless:   true
  delay:      [1, 2]
  batch_size: 10

matcher:
  threshold:  0.7            # only used for the dummy run
  model_path: "models/car_matcher.pkl"
